### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by sEmreCaNw** [sneakyevilSK/SleepingDogs-ModMenu#1]
Hello,i have the Steam version of the game,game instantly crashes when i open,i used the exe provided by you but issue remains,i also tried running the exe as admin.However if i remove the .asi file game loads fine with the dinput8.dll.My friend have the same issue,the mod menu tested on a laptop thats using Windows7 and it worked fine.Im using up to date Windows10.I don't know if the issue related to my computer or not.Thanks in advance.

**Comment by sneakyevilSK** [comment]
If you can, upload the crash dump for me from folder: %LocalAppData%/CrashDumps I can take look at it.

**Comment by sEmreCaNw** [comment]
Thanks,relase v 1.1 working perfect no crash issues.
